### ISSUE TITLE
Customise colour of client admin messages

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#331] opened 2018-06-19 08:47 UTC
As a client administrator
I would like to ensure that messages that come from me for the in-app messaging functionality #259 appear _to the user_ in my brand colours (see #289) 
So that the whole app appears to be correctly branded.

<img width="200" alt="screen shot 2018-06-19 at 02 18 42" src="https://user-images.githubusercontent.com/4185328/41570529-2829aa4e-7367-11e8-8b70-b10ce017bc57.png">

@ajburls Messages from the super admin will always appear in the City deep red. Would you like the messages from client admins to appear in the colour chosen for their banner or for the buttons?

**Comment by ajburls** [comment] 2018-06-19 12:50
@iteles Yes, that sounds sensible.

**Comment by RobStallion** [comment] 2018-09-13 09:10
Duplicate of issue #366

**Closed by RobStallion** 2018-09-13 09:10 UTC
Labels: priority-4
