### ISSUE TITLE
Stage 1 | Show uncertainties in Notes tab

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#369] opened 2018-07-19 08:58 UTC
As a BE user 
I want to see that _all_ of my uncertainties have been captured
So that I know that I have them all and not just the ones appearing in recent searches #367 

## Acceptance Criteria
+ [x] When I click on the 'Collect Uncertainty' button on the homepage, not only does #367 happen, but the uncertainty is saved to my 'Notes' tab, following the existing Notes pattern:
  + [x] The date appears to the left
  + [x] The uncertainty appears to the right
  + [x] Consider that this must be aesthetically pleasing if this is long and drops onto a second line
  + [x] A `?` icon appears to the right of the uncertainty

**Comment by RobStallion** [comment] 2018-07-20 09:26
@iteles based on this point above...
>  Consider that this must be aesthetically pleasing if this is long and drops onto a second line
I have had to change the designs slightly. 

The first screenshot below is following the designs above (not polished but you can see what the problem is I think)
<img width="252" alt="screen shot 2018-07-20 at 10 20 23" src="https://user-images.githubusercontent.com/15571853/42994853-3597ded6-8c07-11e8-84ed-f2baf2df7af9.png">

and the second is the changes I have made to make it work better on mobile 
![image](https://user-images.githubusercontent.com/15571853/42994892-4b778846-8c07-11e8-9f8e-9f7127c8f3fc.png)

Please let me know if you have any thoughts?

**Comment by RobStallion** [comment] 2018-09-13 10:10
Tested with @ajburls. Closing

**Closed by RobStallion** 2018-09-13 10:10 UTC
Labels: please-test, priority-2
